FROM python:3.11-slim-bookworm

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       file \
       git \
       curl \
       jq \
       iproute2 \
       can-utils \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
       pytest \
       pytest-cov \
       junitparser \
       pyserial \
       python-can

WORKDIR /workspace

CMD ["python", "--version"]
